const schools = [
  {
    id: '92e66792-c5cc-43ce-9df5-ad1a2a6f016f',
    npsn: '20401499',
    nama: 'SD Muhammadiyah Bulu',
    jenjang: 'SD/MI',
    alamat: 'Caren, Karangan, Jogotirto, Kec. Berbah, Kabupaten Sleman, Daerah Istimewa Yogyakarta',
    provinsi: 'DI YOGYAKARTA',
    kabupaten: 'KABUPATEN SLEMAN',
    kecamatan: 'Berbah',
    Kelurahan: 'Jogo Tirto',
  },
  {
    id: '56d272c9-7de2-457c-8e6f-262723d53e92',
    npsn: '20401361',
    nama: 'SD Muhammadiyah Karangharjo',
    jenjang: 'SD/MI',
    alamat: 'Jl. Kaliajir Kidul, Bedilan, Kalitirto, Kec. Berbah, Kabupaten Sleman, Daerah Istimewa Yogyakarta',
    provinsi: 'DI YOGYAKARTA',
    kabupaten: 'KABUPATEN SLEMAN',
    kecamatan: 'Berbah',
    Kelurahan: 'Kali Tirto',
  },
  {
    id: 'e88dfbe8-05ef-4e5f-8650-6f67ab23ff37',
    npsn: '20401332',
    nama: 'SD Muhammadiyah Noyokerten',
    jenjang: 'SD/MI',
    alamat: 'Noyokerten, Kadipolo, Sendangtirto, Kec. Berbah, Kabupaten Sleman, Daerah Istimewa Yogyakarta',
    provinsi: 'DI YOGYAKARTA',
    kabupaten: 'KABUPATEN SLEMAN',
    kecamatan: 'Berbah',
    Kelurahan: 'Sendang Tirto',
  },
  {
    id: 'b04ca2c8-fde1-4e4b-a8a3-1c71863a2c7a',
    npsn: '20401331',
    nama: 'SD Muhammadiyah Pajangan 1',
    jenjang: 'SD/MI',
    alamat: 'Dawukan, Sendangtirto, Kec. Berbah, Kabupaten Sleman, Daerah Istimewa Yogyakarta',
    provinsi: 'DI YOGYAKARTA',
    kabupaten: 'KABUPATEN SLEMAN',
    kecamatan: 'Berbah',
    Kelurahan: 'Sendang Tirto',
  },
  {
    id: 'a1840933-e275-430e-a694-0c29d2db0b96',
    npsn: '20401330',
    nama: 'SD Muhammadiyah Pajangan 2',
    jenjang: 'SD/MI',
    alamat: 'Jl. Gandu, Gandu, Sendangtirto, Kec. Berbah, Kabupaten Sleman, Daerah Istimewa Yogyakarta',
    provinsi: 'DI YOGYAKARTA',
    kabupaten: 'KABUPATEN SLEMAN',
    kecamatan: 'Berbah',
    Kelurahan: 'Sendang Tirto',
  },
  {
    id: '6d606007-fa8a-49df-9ffd-260f79a5dd83',
    npsn: '20401336',
    nama: 'SD Muhammadiyah Semoya',
    jenjang: 'SD/MI',
    alamat: 'Semoya, Tegaltirto, Berbah, Sleman Regency, Special Region of Yogyakarta',
    provinsi: 'DI YOGYAKARTA',
    kabupaten: 'KABUPATEN SLEMAN',
    kecamatan: 'Berbah',
    Kelurahan: 'Tegal Tirto',
  },
  {
    id: '4ae58beb-fbfa-4a9b-a36a-0d9734e0459e',
    npsn: '20401479',
    nama: 'SD Muhammadiyah Cepitsari',
    jenjang: 'SD/MI',
    alamat: 'Dengis, Glagaharjo, Kec. Cangkringan, Kabupaten Sleman, Daerah Istimewa Yogyakarta',
    provinsi: 'DI YOGYAKARTA',
    kabupaten: 'KABUPATEN SLEMAN',
    kecamatan: 'Cangkringan',
    Kelurahan: 'Glagah Harjo',
  },
  {
    id: 'd1f74e0d-ab8a-4252-aa58-438de6aab82b',
    npsn: '20401369',
    nama: 'SD Muhammadiyah Kregan',
    jenjang: 'SD/MI',
    alamat: 'Salam Krajan, Wukirsari, Kec. Cangkringan, Kabupaten Sleman, Daerah Istimewa Yogyakarta',
    provinsi: 'DI YOGYAKARTA',
    kabupaten: 'KABUPATEN SLEMAN',
    kecamatan: 'Cangkringan',
    Kelurahan: 'Wukir Sari',
  },
  {
    id: 'd9a2df06-4095-48a4-b7fa-622c4e27ef81',
    npsn: '20401485',
    nama: 'SD Muhammadiyah Condongcatur',
    jenjang: 'SD/MI',
    alamat: 'Jl. Perumnas Gorongan No.1, Ngropoh, Condongcatur, Kec. Depok, Kabupaten Sleman, Daerah Istimewa Yogyakarta',
    provinsi: 'DI YOGYAKARTA',
    kabupaten: 'KABUPATEN SLEMAN',
    kecamatan: 'Depok',
    Kelurahan: 'Condong Catur',
  },
  {
    id: '9deaa262-12fa-4ec1-b358-22195bc11fb0',
    npsn: '20401363',
    nama: 'SD Muhammadiyah Kayen',
    jenjang: 'SD/MI',
    alamat: 'Gg. Kemuning, Kayen, Condongcatur, Kec. Depok, Kabupaten Sleman, Daerah Istimewa Yogyakarta',
    provinsi: 'DI YOGYAKARTA',
    kabupaten: 'KABUPATEN SLEMAN',
    kecamatan: 'Depok',
    Kelurahan: 'Condong Catur',
  },
  {
    id: '5591a9f6-945d-4e8e-96d4-0ff8f5234a9e',
    npsn: '20404085',
    nama: 'SD Muhammadiyah Kolombo',
    jenjang: 'SD/MI',
    alamat: 'Jl. Rajawali No. 10, Demangan Baru',
    provinsi: 'DI YOGYAKARTA',
    kabupaten: 'KABUPATEN SLEMAN',
    kecamatan: 'Depok',
    Kelurahan: 'Catur Tunggal',
  },
  {
    id: '263360d8-5e68-419c-9132-5a5847746475',
    npsn: '20401483',
    nama: 'SD Muhammadiyah Ambarketawang 1',
    jenjang: 'SD/MI',
    alamat: 'Bodeh, Ambarketawang, Kec. Gamping, Kabupaten Sleman, Daerah Istimewa Yogyakarta',
    provinsi: 'DI YOGYAKARTA',
    kabupaten: 'KABUPATEN SLEMAN',
    kecamatan: 'Gamping',
    Kelurahan: 'Ambarketawang',
  },
  {
    id: '41b2a817-f4f7-47ff-ad22-41758f0fa209',
    npsn: '20401482',
    nama: 'SD Muhammadiyah Ambarketawang 2',
    jenjang: 'SD/MI',
    alamat: 'Kalimanjung, Ambarketawang, Kec. Gamping, Kabupaten Sleman, Daerah Istimewa Yogyakarta ',
    provinsi: 'DI YOGYAKARTA',
    kabupaten: 'KABUPATEN SLEMAN',
    kecamatan: 'Gamping',
    Kelurahan: 'Ambarketawang',
  },
  {
    id: 'ab355700-d5a7-4e80-9096-58e13acfe60a',
    npsn: '20401481',
    nama: 'SD Muhammadiyah Ambarketawang 3',
    jenjang: 'SD/MI',
    alamat: 'Gamping Kidul RT. 03 / RW/ 17, Ambarketawang, Gamping Kidul, Ambarketawang, Kec. Gamping, Kabupaten Sleman, Daerah Istimewa Yogyakarta',
    provinsi: 'DI YOGYAKARTA',
    kabupaten: 'KABUPATEN SLEMAN',
    kecamatan: 'Gamping',
    Kelurahan: 'Ambarketawang',
  },
  {
    id: 'c575b69f-5e30-4063-b725-ae8900c54a23',
    npsn: '20401480',
    nama: 'SD Muhammadiyah Balecatur',
    jenjang: 'SD/MI',
    alamat: 'Sumber, Balecatur, Gamping, Sleman Regency, Special Region of Yogyakarta',
    provinsi: 'DI YOGYAKARTA',
    kabupaten: 'KABUPATEN SLEMAN',
    kecamatan: 'Gamping',
    Kelurahan: 'Balecatur',
  },
  {
    id: '2efb1761-5ed9-4afe-99e1-bb07d3f5e69a',
    npsn: '20401491',
    nama: 'SD Muhammadiyah Banyuraden',
    jenjang: 'SD/MI',
    alamat: 'Jl. Tata Bumi Selatan, Dukuh, Banyuraden, Kec. Gamping, Kabupaten Sleman, Daerah Istimewa Yogyakarta',
    provinsi: 'DI YOGYAKARTA',
    kabupaten: 'KABUPATEN SLEMAN',
    kecamatan: 'Gamping',
    Kelurahan: 'Banyuraden',
  },
  {
    id: '38a8ac15-28b9-4c4f-a53b-5a528d27b540',
    npsn: '20401368',
    nama: 'SD Muhammadiyah Kronggahan',
    jenjang: 'SD/MI',
    alamat: 'Jl. Kabupaten No.27, RW.11, Area Sawah, Trihanggo, Kec. Gamping, Kabupaten Sleman, Daerah Istimewa Yogyakarta',
    provinsi: 'DI YOGYAKARTA',
    kabupaten: 'KABUPATEN SLEMAN',
    kecamatan: 'Gamping',
    Kelurahan: 'Trihanggo',
  },
  {
    id: '8aba7517-7290-4b51-a0a6-d4021a3dca0e',
    npsn: '20401366',
    nama: 'SD Muhammadiyah Mlangi',
    jenjang: 'SD/MI',
    alamat: 'Jl. Pundung, Cambahan, Nogotirto, Kec. Gamping, Kabupaten Sleman, Daerah Istimewa Yogyakarta',
    provinsi: 'DI YOGYAKARTA',
    kabupaten: 'KABUPATEN SLEMAN',
    kecamatan: 'Gamping',
    Kelurahan: 'Nogotirto',
  },
  {
    id: '57fc0afa-7b75-4b43-ae22-24069f9b491d',
    npsn: '20401342',
    nama: 'SD Muhammadiyah Trini',
    jenjang: 'SD/MI',
    alamat: 'Trini, Trihanggo, Kec. Gamping, Kabupaten Sleman, Daerah Istimewa Yogyakarta',
    provinsi: 'DI YOGYAKARTA',
    kabupaten: 'KABUPATEN SLEMAN',
    kecamatan: 'Gamping',
    Kelurahan: 'TRIHANGGO',
  },
  {
    id: 'a3faeb62-178c-4696-9471-f80aa80e43e7',
    npsn: '20401371',
    nama: 'SD Muhammadiyah Kliwonan',
    jenjang: 'SD/MI',
    alamat: 'RT.01/RW.17, Kliwonan, Sidorejo, Kec. Godean, Kabupaten Sleman, Daerah Istimewa Yogyakarta',
    provinsi: 'DI YOGYAKARTA',
    kabupaten: 'KABUPATEN SLEMAN',
    kecamatan: 'Godean',
    Kelurahan: 'Sidorejo',
  },
  {
    id: '2b32879d-9ade-42b6-a106-d0a8603aaf71',
    npsn: '20401326',
    nama: 'SD Muhammadiyah Sangonan 1',
    jenjang: 'SD/MI',
    alamat: 'Jl. Ngapak - Kentheng No.13, Sangonan, Sidorejo, Kec. Godean, Kabupaten Sleman, Daerah Istimewa Yogyakarta',
    provinsi: 'DI YOGYAKARTA',
    kabupaten: 'KABUPATEN SLEMAN',
    kecamatan: 'Godean',
    Kelurahan: 'Sidorejo',
  },
  {
    id: '5fd5c137-4c0a-4b61-9d30-6566beccec97',
    npsn: '20401325',
    nama: 'SD Muhammadiyah Sangonan 2',
    jenjang: 'SD/MI',
    alamat: 'Jowah, Sidoluhur, Godean, Pandean, Sidoluhur, Sleman, Kabupaten Sleman, Daerah Istimewa Yogyakarta',
    provinsi: 'DI YOGYAKARTA',
    kabupaten: 'KABUPATEN SLEMAN',
    kecamatan: 'Godean',
    Kelurahan: 'Sidoluhur',
  },
  {
    id: 'b9191e7c-e55d-4ae7-afa2-015a4d5a306a',
    npsn: '20404080',
    nama: 'SD Muhammadiyah Sangonan 3',
    jenjang: 'SD/MI',
    alamat: 'Jl. Genitem, Geninten, Sidoagung, Kec. Godean, Kabupaten Sleman, Daerah Istimewa Yogyakarta',
    provinsi: 'DI YOGYAKARTA',
    kabupaten: 'KABUPATEN SLEMAN',
    kecamatan: 'Godean',
    Kelurahan: 'Sidoagung',
  },
  {
    id: 'c4123cd5-a4e1-41ad-8e5d-69be56a0b5e7',
    npsn: '20401327',
    nama: 'SD Muhammadiyah Sangonan 4',
    jenjang: 'SD/MI',
    alamat: 'Gatak, Sidoluhur, Godean, Sleman, Yogyakarta',
    provinsi: 'DI YOGYAKARTA',
    kabupaten: 'KABUPATEN SLEMAN',
    kecamatan: 'Godean',
    Kelurahan: 'Sidoluhur',
  },
  {
    id: 'ec85f2cd-b37f-443b-bdc2-9ac9986fb26f',
    npsn: '20401337',
    nama: 'SD Muhammadiyah Sidoarum',
    jenjang: 'SD/MI',
    alamat: 'Kramat, Sidoarum, Godean, Sleman Regency, Special Region of Yogyakarta',
    provinsi: 'DI YOGYAKARTA',
    kabupaten: 'KABUPATEN SLEMAN',
    kecamatan: 'Godean',
    Kelurahan: 'Sidoarum',
  },
  {
    id: '43d7ff0c-fdb7-44e3-a781-2a03c3f6663d',
    npsn: '20401348',
    nama: 'SD Muhammadiyah Sidokarto',
    jenjang: 'SD/MI',
    alamat: 'Jetis Prenggan, Sidokarto, Godean, Sleman Regency, Special Region of Yogyakarta',
    provinsi: 'DI YOGYAKARTA',
    kabupaten: 'KABUPATEN SLEMAN',
    kecamatan: 'Godean',
    Kelurahan: 'Sidokarto',
  },
  {
    id: 'c6c7c9d6-3e84-42bb-ab7e-c2169ec6793f',
    npsn: '20401347',
    nama: 'SD Muhammadiyah Sidomulyo',
    jenjang: 'SD/MI',
    alamat: 'Gancakan Wetan, Sidomulyo, Godean, Sleman Regency, Special Region of Yogyakarta',
    provinsi: 'DI YOGYAKARTA',
    kabupaten: 'KABUPATEN SLEMAN',
    kecamatan: 'Godean',
    Kelurahan: 'Sidomulyo',
  },
  {
    id: 'e4b6ac1f-8dd3-4d03-b8e8-514239570d38',
    npsn: '20401492',
    nama: 'SD Muhammadiyah Bayen',
    jenjang: 'SD/MI',
    alamat: 'Bayen, Purwomartani, Kec. Kalasan, Kabupaten Sleman, Daerah Istimewa Yogyakarta',
    provinsi: 'DI YOGYAKARTA',
    kabupaten: 'KABUPATEN SLEMAN',
    kecamatan: 'Kalasan',
    Kelurahan: 'Purwo Martani',
  },
  {
    id: 'd2d45c01-e42c-4047-aee4-468c4ed18f01',
    npsn: '20401497',
    nama: 'SD Muhammadiyah Dhuri',
    jenjang: 'SD/MI',
    alamat: 'Dhuri, Tirtomartani, Kec. Kalasan, Kabupaten Sleman, Daerah Istimewa Yogyakarta',
    provinsi: 'DI YOGYAKARTA',
    kabupaten: 'KABUPATEN SLEMAN',
    kecamatan: 'Kalasan',
    Kelurahan: 'Tirto Martani',
  },
  {
    id: '05f3efed-dd36-4f78-b2da-42cb37d7b12c',
    npsn: '20401328',
    nama: 'SD Muhammadiyah Sambisari',
    jenjang: 'SD/MI',
    alamat: 'Jl. Sambisari Timur, Sambisari, Purwomartani, Kec. Kalasan, Kabupaten Sleman, Daerah Istimewa Yogyakarta',
    provinsi: 'DI YOGYAKARTA',
    kabupaten: 'KABUPATEN SLEMAN',
    kecamatan: 'Kalasan',
    Kelurahan: 'Purwo Martani',
  },
  {
    id: 'b2719990-e301-48bf-be52-df358d1a64b5',
    npsn: '20404084',
    nama: 'SD Muhammadiyah Kadisoka',
    jenjang: 'SD/MI',
    alamat: 'Kadisoko, Purwomartani, Kec. Kalasan, Kabupaten Sleman, Daerah Istimewa Yogyakarta',
    provinsi: 'DI YOGYAKARTA',
    kabupaten: 'KABUPATEN SLEMAN',
    kecamatan: 'Kalasan',
    Kelurahan: 'Purwo Martani',
  },
  {
    id: 'd0efd57f-17e9-4e45-b64e-24f8588d0e4a',
    npsn: '20401372',
    nama: 'SD Muhammadiyah Klepu',
    jenjang: 'SD/MI',
    alamat: 'Klepu, Sendangmulyo, Kec. Minggir, Kabupaten Sleman, Daerah Istimewa Yogyakarta',
    provinsi: 'DI YOGYAKARTA',
    kabupaten: 'KABUPATEN SLEMAN',
    kecamatan: 'Minggir',
    Kelurahan: 'Sendang Mulyo',
  },
  {
    id: '2c07805f-932e-4912-b0e7-4a8348929679',
    npsn: '20404087',
    nama: 'SD Muhammadiyah Ngijon 3',
    jenjang: 'SD/MI',
    alamat: 'Prapak Kulon, Sendang Mulyo, Minggir, Propok Kulon, Sendangmulyo, Sleman, Kabupaten Sleman, Daerah Istimewa Yogyakarta',
    provinsi: 'DI YOGYAKARTA',
    kabupaten: 'KABUPATEN SLEMAN',
    kecamatan: 'Minggir',
    Kelurahan: 'Sendang Mulyo',
  },
  {
    id: 'fb043c82-cf39-4536-bc3a-376465bc8065',
    npsn: '20404088',
    nama: 'SD Muhammadiyah Ngijon 4',
    jenjang: 'SD/MI',
    alamat: 'Badran Kidul, Sendangsari, Kec. Minggir, Kabupaten Sleman, Daerah Istimewa Yogyakarta',
    provinsi: 'DI YOGYAKARTA',
    kabupaten: 'KABUPATEN SLEMAN',
    kecamatan: 'Minggir',
    Kelurahan: 'Sendang Mulyo',
  },
  {
    id: '0d752df9-d2de-45fe-bda2-a6d076c2c8c3',
    npsn: '20401329',
    nama: 'SD Muhammadiyah Plembon',
    jenjang: 'SD/MI',
    alamat: 'Plembon, Sendangsari, Kec. Minggir, Kabupaten Sleman, Daerah Istimewa Yogyakarta',
    provinsi: 'DI YOGYAKARTA',
    kabupaten: 'KABUPATEN SLEMAN',
    kecamatan: 'Minggir',
    Kelurahan: 'Sendangsari',
  },
  {
    id: 'be9bd302-0a3d-4a31-8a78-219adc8247ec',
    npsn: '20401346',
    nama: 'SD Muhammadiyah Sragan',
    jenjang: 'SD/MI',
    alamat: 'Sragan, Banaran XV, Sragan Banaran, Sendangmulyo, Kec. Minggir, Kabupaten Sleman, Daerah Istimewa Yogyakarta',
    provinsi: 'DI YOGYAKARTA',
    kabupaten: 'KABUPATEN SLEMAN',
    kecamatan: 'Minggir',
    Kelurahan: 'Sendang Mulyo',
  },
  {
    id: '7cd7cd31-7867-4130-a01c-480ec7139164',
    npsn: '20401344',
    nama: 'SD Muhammadiyah Sunten',
    jenjang: 'SD/MI',
    alamat: 'Botokan, Sendangrejo, Kec. Minggir, Kabupaten Sleman, Daerah Istimewa Yogyakarta',
    provinsi: 'DI YOGYAKARTA',
    kabupaten: 'KABUPATEN SLEMAN',
    kecamatan: 'Minggir',
    Kelurahan: 'Sendang Rejo',
  },
  {
    id: '1f5768a6-f59c-4795-846f-2e75380b62fa',
    npsn: '20404091',
    nama: 'SD Muhammadiyah Suronandan',
    jenjang: 'SD/MI',
    alamat: 'Soronondan, Sendangrejo, Kec. Minggir, Kabupaten Sleman, Daerah Istimewa Yogyakarta',
    provinsi: 'DI YOGYAKARTA',
    kabupaten: 'KABUPATEN SLEMAN',
    kecamatan: 'Minggir',
    Kelurahan: 'Sendang Rejo',
  },
  {
    id: 'bc3f5d71-1baf-41c4-bc42-9e8f1ee2ea7c',
    npsn: '20401343',
    nama: 'SD Muhammadiyah Tengahan',
    jenjang: 'SD/MI',
    alamat: 'Desa Sendangagung Kec. Minggir, Dukuhan, Sendangagung, Sleman, Kabupaten Sleman, Daerah Istimewa Yogyakarta',
    provinsi: 'DI YOGYAKARTA',
    kabupaten: 'KABUPATEN SLEMAN',
    kecamatan: 'Minggir',
    Kelurahan: 'Sendangagung',
  },
  {
    id: '85bf07a1-9c74-4b00-89f8-e1037a65ec6b',
    npsn: '20404082',
    nama: 'SD Muhammadiyah Blunyah',
    jenjang: 'SD/MI',
    alamat: 'Jl. Monumen Jogja Kembali No.178 B, Kutu Dukuh, Sinduadi, Kec. Mlati, Kabupaten Sleman, Daerah Istimewa Yogyakarta',
    provinsi: 'DI YOGYAKARTA',
    kabupaten: 'KABUPATEN SLEMAN',
    kecamatan: 'Mlati',
    Kelurahan: 'Sinduadi',
  },
  {
    id: '0f14ad58-6632-454b-b636-26af3ad6f0fc',
    npsn: '20404083',
    nama: 'SD Muhammadiyah Gamplong',
    jenjang: 'SD/MI',
    alamat: 'Gamplong, Dukuh, Sumberrahayu, Kec. Moyudan, Kabupaten Sleman, Daerah Istimewa Yogyakarta',
    provinsi: 'DI YOGYAKARTA',
    kabupaten: 'KABUPATEN SLEMAN',
    kecamatan: 'Moyudan',
    Kelurahan: 'Sumberrahayu',
  },
  {
    id: '455c9739-a3cf-4b05-b67f-1f88e750cb94',
    npsn: '20401351',
    nama: 'SD Muhammadiyah Karanganjir',
    jenjang: 'SD/MI',
    alamat: 'Jitar, Sumberarum, Kec. Moyudan, Kabupaten Sleman, Daerah Istimewa Yogyakarta',
    provinsi: 'DI YOGYAKARTA',
    kabupaten: 'KABUPATEN SLEMAN',
    kecamatan: 'Moyudan',
    Kelurahan: 'Sumberarum',
  },
  {
    id: 'ab02001b-8d89-44ff-9358-f6777f153c74',
    npsn: '20401588',
    nama: 'SD Muhammadiyah Kedungbanteng 1',
    jenjang: 'SD/MI',
    alamat: 'Jl. Kedung Banteng, Area Sawah, Sumberagung, Kec. Moyudan, Kabupaten Sleman, Daerah Istimewa Yogyakarta',
    provinsi: 'DI YOGYAKARTA',
    kabupaten: 'KABUPATEN SLEMAN',
    kecamatan: 'Moyudan',
    Kelurahan: 'Sumber Agung',
  },
  {
    id: '21bac373-42d9-460c-a51f-950497847b71',
    npsn: '20401373',
    nama: 'SD Muhammadiyah Kedungbanteng 2',
    jenjang: 'SD/MI',
    alamat: 'Bendosari, Sumbersari, Kec. Moyudan, Kabupaten Sleman, Daerah Istimewa Yogyakarta',
    provinsi: 'DI YOGYAKARTA',
    kabupaten: 'KABUPATEN SLEMAN',
    kecamatan: 'Moyudan',
    Kelurahan: 'Sumbersari',
  },
  {
    id: '6faa5516-716f-4f36-ad59-d059c54ff4a3',
    npsn: '20404086',
    nama: 'SD Muhammadiyah Ngijon 1',
    jenjang: 'SD/MI',
    alamat: 'Turgenen, Sumberagung, Kec. Moyudan, Kabupaten Sleman, Daerah Istimewa Yogyakarta',
    provinsi: 'DI YOGYAKARTA',
    kabupaten: 'KABUPATEN SLEMAN',
    kecamatan: 'Moyudan',
    Kelurahan: 'Sumber Agung',
  },
  {
    id: 'e6dcf7a8-2ee3-4655-b17f-2302e05828c5',
    npsn: '20401587',
    nama: 'SD Muhammadiyah Ngijon 2',
    jenjang: 'SD/MI',
    alamat: 'Sermo, Sumberarum, Kec. Moyudan, Kabupaten Sleman, Daerah Istimewa Yogyakarta',
    provinsi: 'DI YOGYAKARTA',
    kabupaten: 'KABUPATEN SLEMAN',
    kecamatan: 'Moyudan',
    Kelurahan: 'Sumberarum',
  },
  {
    id: 'a7db9ecb-79ff-417c-aaf8-32c3b5c383d1',
    npsn: '20401324',
    nama: 'SD Muhammadiyah Saren',
    jenjang: 'SD/MI',
    alamat: 'Saren, Sumberrahayu, Moyudan, Sleman Regency, Special Region of Yogyakarta',
    provinsi: 'DI YOGYAKARTA',
    kabupaten: 'KABUPATEN SLEMAN',
    kecamatan: 'Moyudan',
    Kelurahan: 'Sumberrahayu',
  },
  {
    id: '3ad3b9cf-00de-452b-8f08-6bb6877a5d04',
    npsn: '20401586',
    nama: 'SD Muhammadiyah Semingin',
    jenjang: 'SD/MI',
    alamat: 'Jl. Sumbersari, Area Sawah, Dakawon, Sumbersari, Kec. Moyudan, Kabupaten Sleman, Daerah Istimewa Yogyakarta',
    provinsi: 'DI YOGYAKARTA',
    kabupaten: 'KABUPATEN SLEMAN',
    kecamatan: 'Moyudan',
    Kelurahan: 'Sumbersari',
  },
  {
    id: 'a82e30c2-31a6-41ee-9e56-b37d137d1d2c',
    npsn: '69971764',
    nama: 'SD Muhammadiyah 1 Ngaglik',
    jenjang: 'SD/MI',
    alamat: 'KLIDON MANTREN, SUKOHARJO, KEC. NGAGLIK, KAB. SLEMAN, D.I. YOGYAKARTA',
    provinsi: 'DI YOGYAKARTA',
    kabupaten: 'KABUPATEN SLEMAN',
    kecamatan: 'Ngaglik',
    Kelurahan: 'Sukoharjo',
  },
  {
    id: 'dc2f74c1-2173-4f40-9711-d58e0caf383b',
    npsn: '20401367',
    nama: 'SD Muhammadiyah Macanan',
    jenjang: 'SD/MI',
    alamat: 'Tambakan, Sindumartani, Kec. Ngemplak, Kabupaten Sleman, Daerah Istimewa Yogyakarta',
    provinsi: 'DI YOGYAKARTA',
    kabupaten: 'KABUPATEN SLEMAN',
    kecamatan: 'Ngemplak',
    Kelurahan: 'Bimo Martani',
  },
  {
    id: 'b3d6e32a-f879-4d59-85d4-513d95340d2f',
    npsn: '69788558',
    nama: 'SD Muhammadiyah 2 pakem',
    jenjang: 'SD/MI',
    alamat: 'Jl. Turgo, Ngepring, Purwobinangun, Kec. Pakem, Kabupaten Sleman, Daerah Istimewa Yogyakarta',
    provinsi: 'DI YOGYAKARTA',
    kabupaten: 'KABUPATEN SLEMAN',
    kecamatan: 'Pakem',
    Kelurahan: 'Purwo Binangun',
  },
  {
    id: 'fb3fbbe6-ae9b-49a0-8894-def25cecc7cb',
    npsn: '20404585',
    nama: 'SD Muhammadiyah Pakem',
    jenjang: 'SD/MI',
    alamat: 'Jl. Kaliurang, No.27, Gambiran, Pakembinangun, Pakem, Sleman, Daerah Istimewa Yogyakarta',
    provinsi: 'DI YOGYAKARTA',
    kabupaten: 'KABUPATEN SLEMAN',
    kecamatan: 'Pakem',
    Kelurahan: 'Pakem Binangun',
  },
  {
    id: '36b973b9-3951-427b-ad5d-0b0077a0158d',
    npsn: '20401502',
    nama: 'SD Muhammadiyah Bendosari',
    jenjang: 'SD/MI',
    alamat: 'Kembang, Madurejo, Kec. Prambanan, Kabupaten Sleman, Daerah Istimewa Yogyakarta',
    provinsi: 'DI YOGYAKARTA',
    kabupaten: 'KABUPATEN SLEMAN',
    kecamatan: 'Prambanan',
    Kelurahan: 'Madu Rejo',
  },
  {
    id: '6fe941f1-5647-4e7a-af95-d975355237a9',
    npsn: '20401501',
    nama: 'SD Muhammadiyah Bleber',
    jenjang: 'SD/MI',
    alamat: 'Gg. Bleber Lor, Berjo, Sumberharjo, Kec. Prambanan, Kabupaten Sleman, Daerah Istimewa Yogyakarta',
    provinsi: 'DI YOGYAKARTA',
    kabupaten: 'KABUPATEN SLEMAN',
    kecamatan: 'Prambanan',
    Kelurahan: 'Sumber Harjo',
  },
  {
    id: 'dd4762ab-0daa-4211-af1c-43df37b7949e',
    npsn: '20401352',
    nama: 'SD Muhammadiyah Gunungharjo 2',
    jenjang: 'SD/MI',
    alamat: 'Losari 1, Wukirharjo, Prambanan, Sleman Regency, Special Region of Yogyakarta',
    provinsi: 'DI YOGYAKARTA',
    kabupaten: 'KABUPATEN SLEMAN',
    kecamatan: 'Prambanan',
    Kelurahan: 'Wukir Harjo',
  },
  {
    id: '82f4e31f-6c71-45d0-b938-0b80eb556d94',
    npsn: '20401353',
    nama: 'SD Muhammadiyah MBS Prambanan',
    jenjang: 'SD/MI',
    alamat: 'Cepit, Bokoharjo, Kec. Prambanan, Kabupaten Sleman, Daerah Istimewa Yogyakarta',
    provinsi: 'DI YOGYAKARTA',
    kabupaten: 'KABUPATEN SLEMAN',
    kecamatan: 'Prambanan',
    Kelurahan: 'Boko Harjo',
  },
  {
    id: 'bd9b370a-e84d-4779-b3a2-59fb65ac8785',
    npsn: '20407341',
    nama: 'SD Muhammadiyah Prambanan',
    jenjang: 'SD/MI',
    alamat: 'Jl. Raya Piyungan - Prambanan, Ringin Sari, Bokoharjo, Kec. Prambanan, Kabupaten Sleman, Daerah Istimewa Yogyakarta',
    provinsi: 'DI YOGYAKARTA',
    kabupaten: 'KABUPATEN SLEMAN',
    kecamatan: 'Prambanan',
    Kelurahan: 'Boko Harjo',
  },
  {
    id: '903da701-7ee9-4351-850e-37d4d53e8fb6',
    npsn: '20401500',
    nama: 'SD Muhammadiyah Bolu',
    jenjang: 'SD/MI',
    alamat: 'Bolu, Margoaton, Kecamatan Seyegan, Kabupaten Sleman, Provinsi Daearah Istimewa Yogyakarta',
    provinsi: 'DI YOGYAKARTA',
    kabupaten: 'KABUPATEN SLEMAN',
    kecamatan: 'Seyegan',
    Kelurahan: 'Margokaton',
  },
  {
    id: '4ea8e287-2c0e-41da-85bc-c01f5182226a',
    npsn: '20401591',
    nama: 'SD Muhammadiyah Gendol 5',
    jenjang: 'SD/MI',
    alamat: 'Mrincingan, Kelurahan Margomulyo, Kecamatan Seyegan, Kabupaten Sleman, Provinsi Daerah IstimewaYogyakarta ',
    provinsi: 'DI YOGYAKARTA',
    kabupaten: 'KABUPATEN SLEMAN',
    kecamatan: 'Seyegan',
    Kelurahan: 'Margomulyo',
  },
  {
    id: '617c2693-b779-466e-9cb2-56161002164f',
    npsn: '20401356',
    nama: 'SD Muhammadiyah Gendol 6',
    jenjang: 'SD/MI',
    alamat: 'Barak 1, Kelurahan Margoluwih, Kecamatan Seyegan, Kabupaten Sleman, Provinsi Daerah IstimewaYogyakarta',
    provinsi: 'DI YOGYAKARTA',
    kabupaten: 'KABUPATEN SLEMAN',
    kecamatan: 'Seyegan',
    Kelurahan: 'Margoluwih',
  },
  {
    id: '5599b1fd-fed5-496b-92c7-01f965049b7e',
    npsn: '20401590',
    nama: 'SD Muhammadiyah Gendol 7',
    jenjang: 'SD/MI',
    alamat: 'Klangkapan, Kelurahan Margoluwih, Kecamatan Seyegan, Kabupaten Bantul, Provinsi Daerah Istimewa Yogyakarta ',
    provinsi: 'DI YOGYAKARTA',
    kabupaten: 'KABUPATEN SLEMAN',
    kecamatan: 'Seyegan',
    Kelurahan: 'Margoluwih',
  },
  {
    id: 'c2c0ca0b-be72-4d30-85bd-043a2ac00b53',
    npsn: '20401362',
    nama: 'SD Muhammadiyah Kasuran',
    jenjang: 'SD/MI',
    alamat: 'Jingin, Kelurahan Margomulyo, Kecamatan Seyegan, Kabupaten Sleman, Provinsi Daerah IstimewaYogyakarta',
    provinsi: 'DI YOGYAKARTA',
    kabupaten: 'KABUPATEN SLEMAN',
    kecamatan: 'Seyegan',
    Kelurahan: 'Margomulyo',
  },
  {
    id: '5e7bb218-268f-42e6-9e53-5ee27f419795',
    npsn: '60714135',
    nama: 'MI Muhammadiyah Al-Muttaqien',
    jenjang: 'SD/MI',
    alamat: 'Medari Cilik, Rt.04/16, Kelurahan Catur Harjo, Kecamatan Sleman, Kabupaten Sleman, Provinsi Daerah IstimewaYogyakarta',
    provinsi: 'DI YOGYAKARTA',
    kabupaten: 'KABUPATEN SLEMAN',
    kecamatan: 'Sleman',
    Kelurahan: 'Catur Harjo',
  },
  {
    id: 'cc14bfd4-341b-4b3b-815c-d879c362aa54',
    npsn: '20401493',
    nama: 'SD Muhammadiyah Domban 4',
    jenjang: 'SD/MI',
    alamat: 'Jl.Panggeran, Kelurahan Triharjo, Kecamatan Sleman, Kabupaten Sleman, Provinsi Daerah Istimewa Yogyakarta',
    provinsi: 'DI YOGYAKARTA',
    kabupaten: 'KABUPATEN SLEMAN',
    kecamatan: 'Sleman',
    Kelurahan: 'Triharjo',
  },
  {
    id: 'c1653764-cb96-41f3-981a-3e80c864b6a1',
    npsn: '69945435',
    nama: 'SD Muhammadiyah Mantaran',
    jenjang: 'SD/MI',
    alamat: 'Jl. Turi KM 3 Mantaran, Kelurahan Tri Mulyono, Kecamatan Sleman, Kabupaten Sleman, Provinsi Daerah Istimewa Yogyakarta ',
    provinsi: 'DI YOGYAKARTA',
    kabupaten: 'KABUPATEN SLEMAN',
    kecamatan: 'Sleman',
    Kelurahan: 'Tri Mulyono',
  },
  {
    id: 'b58be0e4-5e8a-468c-ade6-4f8266ef615b',
    npsn: '20401496',
    nama: 'SD Muhammadiyah Domban 1',
    jenjang: 'SD/MI',
    alamat: 'Karanggawang, Kecamatan Tempel, Kabupaten Sleman, Provinsi Daerah Istimewa Yogyakarta',
    provinsi: 'DI YOGYAKARTA',
    kabupaten: 'KABUPATEN SLEMAN',
    kecamatan: 'Tempel',
    Kelurahan: 'Moro Rejo',
  },
  {
    id: '4613e158-2755-478e-905d-79c4411f2d7a',
    npsn: '20401495',
    nama: 'SD Muhammadiyah Domban 2',
    jenjang: 'SD/MI',
    alamat: 'Karanggawang, Moro Rejo, Kecamatan Tempel, Kabupaten Sleman, Provinsi Daerah Istimewa Yogyakarta ',
    provinsi: 'DI YOGYAKARTA',
    kabupaten: 'KABUPATEN SLEMAN',
    kecamatan: 'Tempel',
    Kelurahan: 'Moro Rejo',
  },
  {
    id: '3ba0559d-a99e-4044-b499-0840353f25d9',
    npsn: '20401494',
    nama: 'SD Muhammadiyah Domban 3',
    jenjang: 'SD/MI',
    alamat: 'Tegal Domban, Margo Rejo, Kecamatan Tempel, Kabupaten Sleman, Provinsi Daerah Istimewa Yogyakarta ',
    provinsi: 'DI YOGYAKARTA',
    kabupaten: 'KABUPATEN SLEMAN',
    kecamatan: 'Tempel',
    Kelurahan: 'Margo Rejo ',
  },
  {
    id: '8181957c-2eb2-4f8c-9b60-3a6227457ae7',
    npsn: '20401360',
    nama: 'SD Muhammadiyah Gendol 1',
    jenjang: 'SD/MI',
    alamat: 'Gendol, Sumber Rejo, Kecamatan Tempel, Kabupaten Sleman, Provinsi Daerah Istimewa Yogyakarta',
    provinsi: 'DI YOGYAKARTA',
    kabupaten: 'KABUPATEN SLEMAN',
    kecamatan: 'Tempel',
    Kelurahan: 'Tempel',
  },
  {
    id: '9b2fcb00-949b-47d9-a88f-d84a9127c6be',
    npsn: '20401358',
    nama: 'SD Muhammadiyah Gendol 3',
    jenjang: 'SD/MI',
    alamat: 'Jl. Medari-Cemoro Blimbingan, Kelurahan Tambak Rejo, Kecamatan Tempel, Kabupaten Sleman, Provinsi Daerah Istimewa Yogyakarta ',
    provinsi: 'DI YOGYAKARTA',
    kabupaten: 'KABUPATEN SLEMAN',
    kecamatan: 'Tempel',
    Kelurahan: 'Tambak Rejo ',
  },
  {
    id: 'e80c89e5-bf85-48e7-b1af-8e6f6983d639',
    npsn: '20401357',
    nama: 'SD Muhammadiyah Gendol 4',
    jenjang: 'SD/MI',
    alamat: 'Krasakan, Kelurahan Lumbung Rejo, Kecamatan Tempel, Kabupaten Sleman, Provinsi Daerah Istimewa Yogyakarta ',
    provinsi: 'DI YOGYAKARTA',
    kabupaten: 'KABUPATEN SLEMAN',
    kecamatan: 'Tempel',
    Kelurahan: 'Lumbung Rejo',
  },
  {
    id: '20d5e50b-5f1c-42fa-b5c3-8a779f00b0ef',
    npsn: '20401354',
    nama: 'SD Muhammadiyah Gondanglegi',
    jenjang: 'SD/MI',
    alamat: 'Gondanglegi, Kelurahan Merdiko Rejo, Kecamatan Tempel, Kabupaten Sleman, Provinsi Daerah IstimewaYogyakarta',
    provinsi: 'DI YOGYAKARTA',
    kabupaten: 'KABUPATEN SLEMAN',
    kecamatan: 'Tempel',
    Kelurahan: 'Merdiko Rejo ',
  },
  {
    id: '3f164efa-008d-486d-9a5d-ae1e093905ad',
    npsn: '20401370',
    nama: 'SD Muhammadiyah Kragan',
    jenjang: 'SD/MI',
    alamat: 'Kragen, Kelurahan Moro Rejo, Kecamatan Tempel,  Kabupaten Sleman, Provinsi Daerah Istimewa Yogyakarta ',
    provinsi: 'DI YOGYAKARTA',
    kabupaten: 'KABUPATEN SLEMAN',
    kecamatan: 'Tempel',
    Kelurahan: 'Moro Rejo ',
  },
  {
    id: '480d9afa-8a9a-4cc9-8c6d-969de5000721',
    npsn: '20401365',
    nama: 'SD Muhammadiyah Ngabean 1',
    jenjang: 'SD/MI',
    alamat: 'Kemusuh, Kelurahan Banyu Rejo, Kecamatan Tempel, Kabupaten Sleman, Daerah Istimewa Yogyakarta ',
    provinsi: 'DI YOGYAKARTA',
    kabupaten: 'KABUPATEN SLEMAN',
    kecamatan: 'Tempel',
    Kelurahan: 'Banyu Rejo ',
  },
  {
    id: 'f143c7ea-8a53-4b69-aa1c-63ce83b2e88f',
    npsn: '20401364',
    nama: 'SD Muhammadiyah Ngabean 2',
    jenjang: 'SD/MI',
    alamat: 'Karang, Kelurahan Banyu Rejo, Kecamatan Tempel, Kabupaten Sleman, Daerah Istimewa Yogakarta ',
    provinsi: 'DI YOGYAKARTA',
    kabupaten: 'KABUPATEN SLEMAN',
    kecamatan: 'Tempel',
    Kelurahan: 'Banyu Rejo ',
  },
  {
    id: 'b525e645-e0a0-477a-b38c-b62f118da0fd',
    npsn: '20401490',
    nama: 'SD Muhammadiyah Balerante',
    jenjang: 'SD/MI',
    alamat: 'Sempu, Kelurahan Wono Kerto, Kecamatan Turi, Kabupaten Sleman, Provinsi Daerah Istimewa Yogyakarta ',
    provinsi: 'DI YOGYAKARTA',
    kabupaten: 'KABUPATEN SLEMAN',
    kecamatan: 'Turi',
    Kelurahan: 'Wono Kerto',
  },
  {
    id: '8bb39288-95f9-4789-b364-a57ba2f9e5f1',
    npsn: '20401498',
    nama: 'SD Muhammadiyah Dadapan',
    jenjang: 'SD/MI',
    alamat: 'Dadapan, Kelurahan Wono Kerto, Kecamatan Turi, Kabupaten Sleman, Provinsi Daerah Istimewa Yogyakarta ',
    provinsi: 'DI YOGYAKARTA',
    kabupaten: 'KABUPATEN SLEMAN',
    kecamatan: 'Turi',
    Kelurahan: 'Wono Kerto',
  },
  {
    id: 'd5e866a6-c270-43fb-9e7e-1989b0ca83f0',
    npsn: '20401355',
    nama: 'SD Muhammadiyah Girikerto',
    jenjang: 'SD/MI',
    alamat: 'Sidorejo, Kelurahan Giri Kerto, Kecamatan Turi, Kabupaten Sleman, Provinsi Daerah Istimewa Yogyakarta ',
    provinsi: 'DI YOGYAKARTA',
    kabupaten: 'KABUPATEN SLEMAN',
    kecamatan: 'Turi',
    Kelurahan: 'Giri Kerto ',
  },
  {
    id: '419abfd0-ff11-402b-88c0-5eddc9b5050c',
    npsn: '20401139',
    nama: 'SMK Muhammadiyah Berbah',
    jenjang: 'SMA/K',
    alamat: 'Krikilan, Kelurahan Tegal Tirto, Kecamatan Berbenah, Kabupaten Sleman, Provinsi Daerah Istimewa Yogyakarta',
    provinsi: 'DI YOGYAKARTA',
    kabupaten: 'KABUPATEN SLEMAN',
    kecamatan: 'Berbah',
    Kelurahan: 'Tegal Tirto ',
  },
  {
    id: 'c05a32fc-c37b-4ca3-a1bb-6a1894280876',
    npsn: '20401138',
    nama: 'SMK Muhammadiyah Cangkringan',
    jenjang: 'SMA/K',
    alamat: 'Jl.Jetis, Jetis Rt/Rw 01/04, Kelurahan Argo Mulyo, Kecamatan Cangkringan, Kabupaten Sleman, Provinsi Daerah Istimewa Yogyakarta ',
    provinsi: 'DI YOGYAKARTA',
    kabupaten: 'KABUPATEN SLEMAN',
    kecamatan: 'Cangkringan',
    Kelurahan: 'Argo Mulyo ',
  },
  {
    id: '4f4f7e8b-c8ad-4ad4-b492-34ab26470a25',
    npsn: '20407390',
    nama: 'SMK Muhammadiyah Gamping',
    jenjang: 'SMA/K',
    alamat: 'Jl.Wates, Km.6 Dempok, Kelurahan Ambarketawang, Kecamatan Gamping, Kabupaten Sleman, Provinsi Daerah Istimewa Yogyakarta ',
    provinsi: 'DI YOGYAKARTA',
    kabupaten: 'KABUPATEN SLEMAN',
    kecamatan: 'Gamping',
    Kelurahan: 'Ambarketawang ',
  },
  {
    id: 'd9ab78e8-2572-47c0-8682-bcc6e7f47b10',
    npsn: '20401147',
    nama: 'SMA Muhammadiyah Kalasan',
    jenjang: 'SMA/K',
    alamat: 'Jl. Dhuri Tirtomartani, Klasan, Keluruhan Tirto Martani, Kecamatan Kalasan, Kabupaten Sleman, Provinsi Daerah Istimewa Yoyakarta ',
    provinsi: 'DI YOGYAKARTA',
    kabupaten: 'KABUPATEN SLEMAN',
    kecamatan: 'Kalasan',
    Kelurahan: 'Tirto Martani',
  },
  {
    id: 'b28bc569-9197-4ba7-acf2-5e7efe026794',
    npsn: '20401177',
    nama: 'SMK Muhammadiyah Kalasan',
    jenjang: 'SMA/K',
    alamat: 'Ngajeg, Kelurahan Tirto Martani, Kecamatan Kalasan, Kabupaten Sleman, Provinsi Daerah Istimewa Yogyakarta',
    provinsi: 'DI YOGYAKARTA',
    kabupaten: 'KABUPATEN SLEMAN',
    kecamatan: 'Kalasan',
    Kelurahan: 'Tirto Martani ',
  },
  {
    id: '8470929e-e2bc-4190-b5db-7d31e6c90403',
    npsn: '20409728',
    nama: 'SMK Muhammadiyah Minggir',
    jenjang: 'SMA/K',
    alamat: 'Sidorejo, Rt/Rw 6/28, Kelurahan Sendang Rejo, Kecamatan Minggir, Kabupaten Sleman, Provinsi Daerah Istimewa Yogyakarta ',
    provinsi: 'DI YOGYAKARTA',
    kabupaten: 'KABUPATEN SLEMAN',
    kecamatan: 'Minggir',
    Kelurahan: 'Sendang Rejo ',
  },
  {
    id: 'fe6c3f50-bd3a-4ba7-8f6e-f1c48d01292a',
    npsn: '20401158',
    nama: 'SMA Muhammadiyah Mlati',
    jenjang: 'SMA/K',
    alamat: 'Jl. Magelang KM.7 Yogyakarta, Sinduadi, Kecamatan Mlati, Kabupaten Sleman, Provinsi Daerah Istimewa Yogyakarta',
    provinsi: 'DI YOGYAKARTA',
    kabupaten: 'KABUPATEN SLEMAN',
    kecamatan: 'Mlati',
    Kelurahan: 'Sinduadi',
  },
  {
    id: '866cd8ee-2d4f-4140-a0b0-e85c1b3a9ba5',
    npsn: '20401319',
    nama: 'SMK Muhammadiyah Mlati',
    jenjang: 'SMA/K',
    alamat: 'Jl. Kaliurang Km.6,5  Gg. Timor-Timur Blok F.04, Kelurahan Sinduadi, Kecamatan Mlati, Kabupaten Sleman, Provinsi Daerah Istimewa Yogyakarta ',
    provinsi: 'DI YOGYAKARTA',
    kabupaten: 'KABUPATEN SLEMAN',
    kecamatan: 'Mlati',
    Kelurahan: 'Sinduadi',
  },
  {
    id: 'c3a23e1d-1b43-4473-b412-2d7c8401b298',
    npsn: '20401176',
    nama: 'SMK Muhammadiyah 1 Moyudan',
    jenjang: 'SMA/K',
    alamat: 'Jl. Klagon - Tempel Km. 4.5, Gendongan, Kelurahan Sumber Agung, Kecamatan Moyudan, Kabupaten Sleman, Provinsi Daerah Istimewa Yogyakarta',
    provinsi: 'DI YOGYAKARTA',
    kabupaten: 'KABUPATEN SLEMAN',
    kecamatan: 'Moyudan',
    Kelurahan: 'Sumber Agung ',
  },
  {
    id: 'bc8fd894-303d-45ee-abe3-29220b2d50bc',
    npsn: '20401140',
    nama: 'SMK Muhammadiyah 2 Moyudan',
    jenjang: 'SMA/K',
    alamat: 'Jl. Moyudan Sedayu, Ngentak, Kelurahan Sumber Agung, kecamatan Moyudan, Kabupaten Sleman, Daerah Istimewa Yogyakarta',
    provinsi: 'DI YOGYAKARTA',
    kabupaten: 'KABUPATEN SLEMAN',
    kecamatan: 'Moyudan',
    Kelurahan: 'Sumber Agung',
  },
  {
    id: 'ef25dc93-279a-4473-b020-82dd3d393f4a',
    npsn: '20401169',
    nama: 'SMA Muhammadiyah Pakem',
    jenjang: 'SMA/K',
    alamat: 'Jl. Kaliurang KM.17 Yogyakarta, Kelurahan Pakem Binangun, Kecamatan Pakem, Kabupaten Sleman, Provinsi Daerah Istimewa Yogyakarta ',
    provinsi: 'DI YOGYAKARTA',
    kabupaten: 'KABUPATEN SLEMAN',
    kecamatan: 'Pakem',
    Kelurahan: 'Pakem Binangun ',
  },
  {
    id: '510b0c62-3467-4c6d-a04b-00399f00972c',
    npsn: '20401318',
    nama: 'SMK Muhammadiyah Pakem',
    jenjang: 'SMA/K',
    alamat: 'Jl. Pakem-Turi km 0.5, Kelurahan Pakem Binangunan, Kecamatan Pakem, Kabupaten Sleman, Provinsi Daerah Istimewa Yogyakarta ',
    provinsi: 'DI YOGYAKARTA',
    kabupaten: 'KABUPATEN SLEMAN',
    kecamatan: 'Pakem',
    Kelurahan: 'Pakem Binangunan ',
  },
  {
    id: '800558f5-6060-4373-bb63-8d8d029c7cab',
    npsn: '60724851',
    nama: 'SMA MBS Prambanan',
    jenjang: 'SMA/K',
    alamat: 'Jl. Piyungan Km. 2 Marangan, Kelurahan Boko Harjo, Kecamatan Prambanan, Kabupaten Sleman, Provinsi Daerah Istimewa Yogyakarta ',
    provinsi: 'DI YOGYAKARTA',
    kabupaten: 'KABUPATEN SLEMAN',
    kecamatan: 'Prambanan',
    Kelurahan: 'Boko Harjo',
  },
  {
    id: 'b49a934b-c2ca-4d97-b8d1-313cb74e6437',
    npsn: '20401152',
    nama: 'SMA Muhammadiyah Prambanan',
    jenjang: 'SMA/K',
    alamat: 'Jl.Gatak, Kelurahan Boko Harjo, Kecamatan Prambanan, Kabupaten Sleman, Provinsi Daerah Istimewa Yogyakarta ',
    provinsi: 'DI YOGYAKARTA',
    kabupaten: 'KABUPATEN SLEMAN',
    kecamatan: 'Prambanan',
    Kelurahan: 'Boko Harjo ',
  },
  {
    id: '8f967c71-cbd0-4708-b515-9b2b58dd810c',
    npsn: '20401317',
    nama: 'SMK Muhammadiyah Prambanan',
    jenjang: 'SMA/K',
    alamat: 'Jl. Prambanan - Piyungan KM.1, Kelurahan Boko Harjo, Kecamatan Prambanan, Kabupaten Slema, Provinsi Daerah Istimewa Yogyakarta ',
    provinsi: 'DI YOGYAKARTA',
    kabupaten: 'KABUPATEN SLEMAN',
    kecamatan: 'Prambanan',
    Kelurahan: 'Boko Harjo ',
  },
  {
    id: 'f228442f-3fd6-4fa9-a4a9-d50d7d097613',
    npsn: '20409729',
    nama: 'SMK Muhammadiyah Seyegan',
    jenjang: 'SMA/K',
    alamat: 'Jl. Seyegan - Tempel KM. 1.1, Krapyak Rt/Rw 6/26, Kelurahan Margoagung, Kecamatan Seyegan, Kabupaten Sleman, Provinsi Daerah Istimewa Yogyakarta ',
    provinsi: 'DI YOGYAKARTA',
    kabupaten: 'KABUPATEN SLEMAN',
    kecamatan: 'Seyegan',
    Kelurahan: 'Margoagung',
  },
  {
    id: '598895c4-bb56-47b7-8250-065ef2b13d07',
    npsn: '20401151',
    nama: 'SMA Muhammadiyah Sleman',
    jenjang: 'SMA/K',
    alamat: 'Jl. Magelang KM. 13 Sleman, Kelurahan Triharjo, Kecamatan Sleman, Kabupaten Sleman, Provinsi Daerah Istimewa Yogyakarta ',
    provinsi: 'DI YOGYAKARTA',
    kabupaten: 'KABUPATEN SLEMAN',
    kecamatan: 'Sleman',
    Kelurahan: 'Triharjo ',
  },
  {
    id: '5f217a72-f1da-4c81-8f5e-d25c314e854d',
    npsn: '20401198',
    nama: 'SMK Muhammadiyah 1 Sleman',
    jenjang: 'SMA/K',
    alamat: 'Jl. Agrowisata, KM 01, Kelurahan Triharjo, Kecamatan Sleman, Kabupaten Sleman, Provinsi Daerah Istimewa Yogyakarta ',
    provinsi: 'DI YOGYAKARTA',
    kabupaten: 'KABUPATEN SLEMAN',
    kecamatan: 'Sleman',
    Kelurahan: 'Triharjo ',
  },
  {
    id: 'e88b0332-6a5e-4076-9c50-b521c20ebd1c',
    npsn: '20401175',
    nama: 'SMK Muhammadiyah 2 Sleman',
    jenjang: 'SMA/K',
    alamat: 'Jl. D Ronggowarsito, No.2 Medari, Kelurahan Catur Harjo, Kecamatan Sleman, Kabupaten Sleman, Provinsi Daerah Istimewa Yogyakarta ',
    provinsi: 'DI YOGYAKARTA',
    kabupaten: 'KABUPATEN SLEMAN',
    kecamatan: 'Sleman',
    Kelurahan: 'Catur Harjo ',
  },
  {
    id: 'f2348390-0c98-434c-9097-bee83affbf94',
    npsn: '20401142',
    nama: 'SMK Muhammadiyah 1 Tempel',
    jenjang: 'SMA/K',
    alamat: 'Sanggrahan, Kelurahan Moro Rejo, Kecamatan Tempel, Kabupaten Sleman, Provinsi Daerah Istimewa Yogyakarta ',
    provinsi: 'DI YOGYAKARTA',
    kabupaten: 'KABUPATEN SLEMAN',
    kecamatan: 'Tempel',
    Kelurahan: 'Moro Rejo ',
  },
  {
    id: '1e30b351-59c6-40df-8c11-7b8e313761eb',
    npsn: '20401174',
    nama: 'SMK Muhammadiyah 2 Tempel',
    jenjang: 'SMA/K',
    alamat: 'Gendol, Sumberejo, Kec. Tempel, Kabupaten Sleman, Daerah Istimewa Yogyakarta',
    provinsi: 'DI YOGYAKARTA',
    kabupaten: 'KABUPATEN SLEMAN',
    kecamatan: 'Tempel',
    Kelurahan: 'Sumberejo',
  },
  {
    id: '1c0476d3-a766-47ad-980c-fcea63476761',
    npsn: '20401141',
    nama: 'SMK Muhammadiyah 1 Turi',
    jenjang: 'SMA/K',
    alamat: 'Keringan,, Wono Kerto, Turi, Sangurejo, Wono Kerto, Kec. Sleman, Kabupaten Sleman, Daerah Istimewa Yogyakarta',
    provinsi: 'DI YOGYAKARTA',
    kabupaten: 'KABUPATEN SLEMAN',
    kecamatan: 'Turi',
    Kelurahan: 'Wono Kerto',
  },
  {
    id: 'e0a400b2-3bc5-44de-9d5b-812b8246010b',
    npsn: '20401310',
    nama: 'SMK Muhammadiyah 2 Turi',
    jenjang: 'SMA/K',
    alamat: 'Jl. Turi-Tempel Km. 3,5 Ngablak, Bangunkerto, Turi, Sleman, Daerah Istimewa Yogyakarta',
    provinsi: 'DI YOGYAKARTA',
    kabupaten: 'KABUPATEN SLEMAN',
    kecamatan: 'Turi',
    Kelurahan: 'Bangunkerto',
  },
  {
    id: '0b316e62-c771-4b98-8cca-f7370632cf32',
    npsn: '20401057',
    nama: 'SMP Muhammadiyah 1 Berbah',
    jenjang: 'SMP',
    alamat: 'Jl. Berbah-Krikilan No.20, Krikilan, Tegaltirto, Kec. Berbah, Kabupaten Sleman, Daerah Istimewa Yogyakarta',
    provinsi: 'DI YOGYAKARTA',
    kabupaten: 'KABUPATEN SLEMAN',
    kecamatan: 'Berbah',
    Kelurahan: 'Tegaltirto',
  },
  {
    id: 'ee3c2b2a-7e7b-4008-b92a-5cb057dcb829',
    npsn: '20401013',
    nama: 'SMP Muhammadiyah 1 Depok',
    jenjang: 'SMP',
    alamat: 'Jl. Stan, Sefan, Maguwoharjo, Kec. Depok, Kabupaten Sleman, Daerah Istimewa Yogyakarta',
    provinsi: 'DI YOGYAKARTA',
    kabupaten: 'KABUPATEN SLEMAN',
    kecamatan: 'Depok',
    Kelurahan: 'MAGUWOHARJO',
  },
  {
    id: 'e117d350-d3ce-40a2-a736-0094d264d237',
    npsn: '20401051',
    nama: 'SMP Muhammadiyah 2 Depok',
    jenjang: 'SMP',
    alamat: 'Jl. Swadaya 4, Karang Asem, Condongcatur, Kec. Depok, Kabupaten Sleman, Daerah Istimewa Yogyakarta',
    provinsi: 'DI YOGYAKARTA',
    kabupaten: 'KABUPATEN SLEMAN',
    kecamatan: 'Depok',
    Kelurahan: 'Condongcatur',
  },
  {
    id: '8d326f37-9357-42fc-bc75-c71d93a40869',
    npsn: '20401048',
    nama: 'SMP Muhammadiyah 3 Depok',
    jenjang: 'SMP',
    alamat: 'Jl. Rajawali 10 Demangan Baru, Caturtunggal, Depok, Sleman, Yogyakarta',
    provinsi: 'DI YOGYAKARTA',
    kabupaten: 'KABUPATEN SLEMAN',
    kecamatan: 'Depok',
    Kelurahan: 'Caturtunggal',
  },
  {
    id: '214abf7c-218b-471c-a325-373f370a8198',
    npsn: '20404587',
    nama: 'SMP Muhammadiyah 1 Gamping',
    jenjang: 'SMP',
    alamat: 'Jl. Wates No.KM.6, Depok, Ambarketawang, Kec. Gamping, Kabupaten Sleman, Daerah Istimewa Yogyakarta',
    provinsi: 'DI YOGYAKARTA',
    kabupaten: 'KABUPATEN SLEMAN',
    kecamatan: 'Gamping',
    Kelurahan: 'Ambarketawang ',
  },
  {
    id: '9d329e28-893c-45d5-a861-5dfce04f85fa',
    npsn: '20401050',
    nama: 'SMP Muhammadiyah 2 Gamping',
    jenjang: 'SMP',
    alamat: 'JL. GODEAN KM.5 Guyangan, Nogotirto, Kec. Gamping, Kab. Sleman Prov. D.I. Yogyakarta ',
    provinsi: 'DI YOGYAKARTA',
    kabupaten: 'KABUPATEN SLEMAN',
    kecamatan: 'Gamping',
    Kelurahan: 'Nogotirto',
  },
  {
    id: '43ed4a6b-570f-4906-818d-dc3bcab244a8',
    npsn: '20401056',
    nama: 'SMP Muhammadiyah 1 Godean',
    jenjang: 'SMP',
    alamat: 'Jl. Suparjo No.36, Mertosutan, Sidoluhur, Kec. Godean, Kabupaten Sleman, Daerah Istimewa Yogyakarta',
    provinsi: 'DI YOGYAKARTA',
    kabupaten: 'KABUPATEN SLEMAN',
    kecamatan: 'Godean',
    Kelurahan: 'SIDOLUHUR',
  },
  {
    id: '0cd19d7c-121f-4e1b-9e93-ebc235c52a0d',
    npsn: '20404132',
    nama: 'SMP Muhammadiyah 2 Godean',
    jenjang: 'SMP',
    alamat: 'Sembuh Lor, Area Sawah, Sidomulyo, Kec. Godean, Kabupaten Sleman, Daerah Istimewa Yogyakarta',
    provinsi: 'DI YOGYAKARTA',
    kabupaten: 'KABUPATEN SLEMAN',
    kecamatan: 'Godean',
    Kelurahan: 'SIDOMULYO',
  },
  {
    id: '70d0bfb1-73b5-4601-a5e3-9fe2a1426e68',
    npsn: '20401017',
    nama: 'SMP Muhammadiyah 1 Kalasan',
    jenjang: 'SMP',
    alamat: 'Jl. Jogja - Solo No.3, Karang Kalasan, Tirtomartani, Kec. Kalasan, Kabupaten Sleman, Daerah Istimewa Yogyakarta',
    provinsi: 'DI YOGYAKARTA',
    kabupaten: 'KABUPATEN SLEMAN',
    kecamatan: 'Kalasan',
    Kelurahan: 'Tirto Martani',
  },
  {
    id: '922d21fe-dd70-4d93-97e7-28dbcab8e3ee',
    npsn: '20401033',
    nama: 'SMP Muhammadiyah 2 Kalasan',
    jenjang: 'SMP',
    alamat: 'Jl. Cangkringan Km. 3 Bayen, Purwomartani, Kalasan, Sleman Regency, Special Region of Yogyakarta',
    provinsi: 'DI YOGYAKARTA',
    kabupaten: 'KABUPATEN SLEMAN',
    kecamatan: 'Kalasan',
    Kelurahan: 'PURWO MARTANI',
  },
  {
    id: '807a3c26-128b-495a-bafb-572c3431e420',
    npsn: '20401055',
    nama: 'SMP Muhammadiyah 1 Minggir',
    jenjang: 'SMP',
    alamat: 'Singojayan, Sendangarum, Kec. Minggir, Kabupaten Sleman, Daerah Istimewa Yogyakarta',
    provinsi: 'DI YOGYAKARTA',
    kabupaten: 'KABUPATEN SLEMAN',
    kecamatan: 'Minggir',
    Kelurahan: 'SENDANG ARUM',
  },
  {
    id: 'a1e5b055-927c-4398-a802-77416fbb72fd',
    npsn: '20404125',
    nama: 'SMP Muhammadiyah 2 Mingir',
    jenjang: 'SMP',
    alamat: 'Parakan, Sendangsari, Parakan Wetan, Sendangsari, Kec. Sleman, Kabupaten Sleman, Daerah Istimewa Yogyakarta',
    provinsi: 'DI YOGYAKARTA',
    kabupaten: 'KABUPATEN SLEMAN',
    kecamatan: 'Minggir',
    Kelurahan: 'SENDANGSARI',
  },
  {
    id: '3a175c6d-daa9-4218-8b00-81e85fab7f53',
    npsn: '20401054',
    nama: 'SMP Muhammadiyah 1 Mlati',
    jenjang: 'SMP',
    alamat: 'Jl. Magelang Km. 7.5, Sendangadi, Mlati, Mlati Glondong, Sendangadi, Kec. Mlati, Kabupaten Sleman, Daerah Istimewa Yogyakarta',
    provinsi: 'DI YOGYAKARTA',
    kabupaten: 'KABUPATEN SLEMAN',
    kecamatan: 'Mlati',
    Kelurahan: 'SENDANGADI',
  },
  {
    id: '99d5ff6d-3ee2-491e-8521-9fd5e7f55225',
    npsn: '20401049',
    nama: 'SMP Muhammadiyah 2 Mlati',
    jenjang: 'SMP',
    alamat: 'Jalan Kaliurang Km 6,7, Gang Timor-timor, Sinduadi, Mlati, Sleman',
    provinsi: 'DI YOGYAKARTA',
    kabupaten: 'KABUPATEN SLEMAN',
    kecamatan: 'Mlati',
    Kelurahan: 'SINDUADI',
  },
  {
    id: 'c4939b38-96c2-46da-826a-c6b95c476474',
    npsn: '20401034',
    nama: 'SMP Muhammadiyah 3 Mlati',
    jenjang: 'SMP',
    alamat: 'Jl. Kebon Agung No.88, Area Sawah, Tlogoadi, Kec. Mlati, Kabupaten Sleman, Daerah Istimewa Yogyakarta',
    provinsi: 'DI YOGYAKARTA',
    kabupaten: 'KABUPATEN SLEMAN',
    kecamatan: 'Mlati',
    Kelurahan: 'Tlogoadi ',
  },
  {
    id: '15757a93-bb2a-48e7-b5cd-42770e81905d',
    npsn: '20401015',
    nama: 'SMP Muhammadiyah 1 Moyudan',
    jenjang: 'SMP',
    alamat: 'Jl. Klangon Tempel, Barepan, Sumberrahayu, Kec. Moyudan, Kabupaten Sleman, Daerah Istimewa Yogyakarta',
    provinsi: 'DI YOGYAKARTA',
    kabupaten: 'KABUPATEN SLEMAN',
    kecamatan: 'Moyudan',
    Kelurahan: 'SUMBERRAHAYU',
  },
  {
    id: '713e085b-9db2-4ec2-9ebc-3f54125e8d4c',
    npsn: '20404127',
    nama: 'SMP Muhammadiyah Ngemplak',
    jenjang: 'SMP',
    alamat: 'Banjarharjo, Bimomartani, Ngemplak, Jaten, Bimomartani, Sleman, Kabupaten Sleman, Daerah Istimewa Yogyakarta',
    provinsi: 'DI YOGYAKARTA',
    kabupaten: 'KABUPATEN SLEMAN',
    kecamatan: 'Ngemplak',
    Kelurahan: 'BIMO MARTANI',
  },
  {
    id: 'b1a2b776-efa8-4c62-b4eb-90459255e48a',
    npsn: '20404124',
    nama: 'SMP Muhammadiyah Pakem',
    jenjang: 'SMP',
    alamat: 'Jalan Kaliurang Km. 17 Tegalsari, Area Sawah, Pakembinangun, Kec. Pakem, Kabupaten Sleman, Daerah Istimewa Yogyakarta',
    provinsi: 'DI YOGYAKARTA',
    kabupaten: 'KABUPATEN SLEMAN',
    kecamatan: 'Pakem',
    Kelurahan: 'Pakem Binangun',
  },
  {
    id: '7283a6eb-d754-45d0-a34c-947cf70a8a6b',
    npsn: '20407422',
    nama: 'SMP MBS Prambanan',
    jenjang: 'SMP',
    alamat: 'Jl Piyungan Km 2 Marangan, Bokoharjo, Kec. Prambanan, Kab. SLeman, D.I. Yogyakarta',
    provinsi: 'DI YOGYAKARTA',
    kabupaten: 'KABUPATEN SLEMAN',
    kecamatan: 'Prambanan',
    Kelurahan: 'Boko Harjo',
  },
  {
    id: 'e3bbb1aa-37ef-486b-932b-e1de70591d87',
    npsn: '20401053',
    nama: 'SMP Muhammadiyah 1 Prambanan',
    jenjang: 'SMP',
    alamat: 'Jl. Raya Piyungan - Prambanan No.Km.1, Gatak, Bokoharjo, Kec. Prambanan, Kabupaten Sleman, Daerah Istimewa Yogyakarta ',
    provinsi: 'DI YOGYAKARTA',
    kabupaten: 'KABUPATEN SLEMAN',
    kecamatan: 'Prambanan',
    Kelurahan: 'Boko Harjo',
  },
  {
    id: '20c1e2a5-88d5-46f1-b899-3a7490dc1ce6',
    npsn: '20404126',
    nama: 'SMP Muhammadiyah 2 Prambanan',
    jenjang: 'SMP',
    alamat: 'Jl. Raya Piyungan - Prambanan No.Km 5, RW.5, Dinginan, Sumberharjo, Kec. Prambanan, Kabupaten Sleman, Daerah Istimewa Yogyakarta',
    provinsi: 'DI YOGYAKARTA',
    kabupaten: 'KABUPATEN SLEMAN',
    kecamatan: 'Prambanan',
    Kelurahan: 'SUMBER HARJO',
  },
  {
    id: '0a7110bb-955a-4c75-b7a3-fb822b093683',
    npsn: '20401052',
    nama: 'SMP Muhammadiyah Seyegan',
    jenjang: 'SMP',
    alamat: 'Grogol, Margodadi, Seyegan, Sleman Regency, Special Region of Yogyakarta',
    provinsi: 'DI YOGYAKARTA',
    kabupaten: 'KABUPATEN SLEMAN',
    kecamatan: 'Seyegan',
    Kelurahan: 'MARGODADI',
  },
  {
    id: 'a9fd039f-197c-431f-a5e8-edd13cbb7f1f',
    npsn: '20401014',
    nama: 'SMP Muhammadiyah 1 Sleman',
    jenjang: 'SMP',
    alamat: 'Panggeran, Panggeran 12, Triharjo, Kec. Sleman, Kabupaten Sleman, Daerah Istimewa Yogyakarta',
    provinsi: 'DI YOGYAKARTA',
    kabupaten: 'KABUPATEN SLEMAN',
    kecamatan: 'Sleman',
    Kelurahan: 'TRIHARJO',
  },
  {
    id: 'ef5852fb-c7ca-4d2f-9b99-8bde49d8f07d',
    npsn: '20401018',
    nama: 'SMP Muhammadiyah 1 Tempel',
    jenjang: 'SMP',
    alamat: 'Jl. Tempel-Seyegan, Gendol, Sumberejo, Kec. Tempel, Kabupaten Sleman, Daerah Istimewa Yogyakarta',
    provinsi: 'DI YOGYAKARTA',
    kabupaten: 'KABUPATEN SLEMAN',
    kecamatan: 'Tempel',
    Kelurahan: 'SUMBER REJO',
  },
  {
    id: '83c5f875-f721-4a03-90d4-6ca09ee837fc',
    npsn: '20401011',
    nama: 'SMP Muhammadiyah Turi',
    jenjang: 'SMP',
    alamat: 'Keringan Wonokerto Turi Sleman Yogyakarta, Kabupaten Sleman, D I Yogyakarta',
    provinsi: 'DI YOGYAKARTA',
    kabupaten: 'KABUPATEN SLEMAN',
    kecamatan: 'Turi',
    Kelurahan: 'Wonokerto ',
  },
  {
    id: 'e0283480-eade-41b2-85a4-f54c3813e455',
    npsn: '20201034',
    nama: 'PDM Sleman',
    jenjang: 'PDM',
    alamat: 'Sawahan, Pandowoharjo, Kec. Sleman, Kabupaten Sleman, Daerah Istimewa Yogyakarta',
    provinsi: 'DI YOGYAKARTA',
    kabupaten: 'KABUPATEN SLEMAN',
    kecamatan: 'Pandowoharjo',
    Kelurahan: 'Sawahan',
  },
];

export default schools;
